### ISSUE TITLE
navigation  next not work

### ISSUE THREAD

**Issue by azarzaza** [st3ph/jquery.easyPaginate#4] opened 2017-01-03 08:48 UTC
navigation previous and next not working when click it will reload the page

**Comment by mvosz** [comment] 2017-01-17 08:34
jupp, same problem

**Comment by ecarpio** [comment] 2017-03-27 16:15
Same problem - I guess there's no support for this plugin

**Comment by st3ph** [comment] 2017-03-27 17:41
As it's the first time this kind of bug is reported, please consider adding more details of your settings and how to reproduce the problem

**Comment by ecarpio** [comment] 2017-03-27 17:48
Right now when I click on next or previous it reloads the entire page. 
Clicking on the numbers and first and last page is OK. Clicking on Previous and Next Reloads entire page.
I placed a break point on the on the NEXT click event and It looks like its skipping that function when I click on Next or previous. But it does hit the breakpoint when the page is first loaded. 

This function does not fire on click.
`$(elSelector + ' .easyPaginateNav a.next', plugin).on('click', function (e) {
                    e.preventDefault();
                    page = plugin.settings.currentPage < plugin.settings.pages ? parseInt(plugin.settings.currentPage) + 1 : plugin.settings.pages;
                    displayPage(page);
                });`

**Comment by ecarpio** [comment] 2017-03-27 18:47
I used the JS file from your demo page and it works.

you might want to diff your source file on github

**Comment by sed8908** [comment] 2017-03-29 13:26
I was experiencing that problem as well. I went in and on lines 96 and 102 and I removed ", plugin" from both lines. That seems to have fixed the problem I was experiencing. Let me know if this change fixes it for anyone else.

**Comment by st3ph** [comment] 2017-04-04 15:45
Fixed with version 1.2 (and current master)

**Closed as completed by st3ph** 2017-04-04 15:45 UTC
